services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - sqlite_data:/root
    environment:
      - ENV=dev
    restart: unless-stopped

volumes:
  sqlite_data:
